apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff-container
        image: us-east1-docker.pkg.dev/no-monolitos/microservicios/bff:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 8003
        env:
        - name: "DB_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "DB_PASSWORD"
              name: "microservicios-config-sxhk"
        - name: "DB_USERNAME"
          valueFrom:
            configMapKeyRef:
              key: "DB_USERNAME"
              name: "microservicios-config-sxhk"
        - name: "DB_HOSTNAME"
          valueFrom:
            configMapKeyRef:
              key: "DB_HOSTNAME"
              name: "microservicios-config-sxhk"
        - name: "BROKER_CONNECTION_STRING"
          valueFrom:
            configMapKeyRef:
              key: "BROKER_CONNECTION_STRING"
              name: "microservicios-config-sxhk"
        - name: "BROKER_JWT_AUTH"
          valueFrom:
            configMapKeyRef:
              key: "BROKER_JWT_AUTH"
              name: "microservicios-config-sxhk"
        - name: "BROKER_HOST"
          valueFrom:
            configMapKeyRef:
              key: "BROKER_HOST"
              name: "microservicios-config-sxhk"

---

apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  selector:
    app: bff
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8003
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: bff-service
            port:
              name: http
