apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordenes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordenes
  template:
    metadata:
      labels:
        app: ordenes
    spec:
      containers:
      - name: ordenes-container
        image: us-east1-docker.pkg.dev/no-monolitos/microservicios/ordenes:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 5000
        env:
        - name: "DB_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "DB_PASSWORD"
              name: "microservicios-config-sxhk"
        - name: "DB_USERNAME"
          valueFrom:
            configMapKeyRef:
              key: "DB_USERNAME"
              name: "microservicios-config-sxhk"
        - name: "DB_HOSTNAME"
          valueFrom:
            configMapKeyRef:
              key: "DB_HOSTNAME"
              name: "microservicios-config-sxhk"
        - name: "BROKER_CONNECTION_STRING"
          valueFrom:
            configMapKeyRef:
              key: "BROKER_CONNECTION_STRING"
              name: "microservicios-config-sxhk"
        - name: "BROKER_JWT_AUTH"
          valueFrom:
            configMapKeyRef:
              key: "BROKER_JWT_AUTH"
              name: "microservicios-config-sxhk"